name: shasfacrm
description: An app build with the stacked framework

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pocketbase: ^0.14.1
  rive: ^0.11.14
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  # - images/a_dot_ham.jpeg

  fonts:
    - family: Anjoman
      fonts:
        - asset: web/assets/fonts/AnjomanMaxVF.ttf
